# Generated by Django 4.1.3 on 2022-12-01 11:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
        ('experiance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiance',
            name='resume_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='resume.resume'),
            preserve_default=False,
        ),
    ]
